## Excercises on conduction {#sec-conductionx}

### Steel plate thermal constant

A 2 mm steel plate with an initial tempeprature, $T_i$ = 20°C is suddelnly exposed on both sides to a gas temperature, $T_f$ = 500°C. Assume a constant heat transfer coefficent, $h$ = 20 W/m²K and the steel properties $c$ = 460 J/kgK and $\rho$ = 7850 kg/m³.

(a) Calculate the thermal time constant of the steel plate.
(b) Calculate the temperature of the steel plate after 5 min.

**Solution**

(a) The thermal time constant is calculated according to

$$
\tau = \frac{dc\rho}{h} = \frac{\tfrac{0.002}{2}460\cdot 7850}{20} = 181 s
$$

note that the thickness, $d$, is divided by half as the plate is exposed on both sides.

(b) At time $t$ = 300 , the steel temperature is then calculated as

$$
T_s = T_i + \left( T_f - T_i \right) \left( 1 - e^{-\tfrac{t}{\tau}} \right) = 20 + \left( 500 - 20 \right)\left( 1 - e^{-\tfrac{300}{181}} \right) = 409°C
$$

### Steel bulkhead

A 5 mm steel bulkhead is suddenly exposed to a fire. It is insulated on the fire-exposed side and unisulated on the unexposed side. 

Boundary conditions on the fire-exposed side
* Temperature, $T_f$ = 1000°C
* Heat transfer coefficient negligable (assume $T_s$ = $T_f$) 

| $d_i$ [mm]  | Material         | $\lambda$ [W/mK] | $c$ [J/kgK] | $\rho$ [kg/m³] |
|:-----:|:-----------------|:-------:|:------:|:------:|
| 100   | Insulation       | 0.07    |    -   |   -    |
| 5     | Steel            | 0.04    | 460    | 7850   |
: {#tbl-bht1}

Boundary conditions on the unexposed side
* Temperature, $T_\infty$ = 20°C
* Heat transfer coefficient $h$ = 5 W/m²K 

What is the ultimate steel temperature, $T_s^{ult}$?

**Solution**

(a) $T_s^{ult}$ can be found when the temperature change is zero. This occurs when the heat entering the steel equal the heat exiting.

The heat entering the steel can be described as the heat passing through the insulation, 

$$
\dot{q}_{in}^{''}=\frac{\lambda_s}{d_s}\left(T_f - T_s\right)
$$

The heat exiting the steel can be described as

$$
\dot{q}_{out}^{''}=h\left(T_{\infty} - T_s \right) 
$$

These two are equal when $T_s$ = $T_s^{ult}$. This can be found by using 

$$
T_s^{ult}=\frac{\tfrac{k}{d}T_f + hT_{\infty}}{\tfrac{k}{f} + h} = 
\frac{\tfrac{0.07}{0.1}1000 + 5\cdot 20}{\tfrac{0.07}{0.1} + 5} = 140°C
$$

### Thermal penetration depth

The surface temperature of a thick concrete wall with an initial temperature of 0°C rises suddely to 1000°C.

(a) What is the 1 % thermal penetration depth, $\delta_{0.01}$, after 15 minutes?
(b) What is the temperature, $T$ at that point after 60 minutes?

Assume the thermal properties of the concrete to be 

* $c$ = 900 J/kgK
* $\rho$ = 2300 kg/m³
* $\lambda$ = 1.5 W/mK

**Solution**

(a) By calculating 

$$
\alpha = \frac{\lambda}{c \rho} = \frac{1.5}{900 \cdot 2300} = 7.25 \cdot 10^{-7}
$$

The penetration depth after 15 minutes (900 s) can be calculated using

$$
\delta_{0.01} = 3.6 \sqrt{\alpha t} = 3.6 \sqrt{7.25 \cdot 10^{-7} \cdot 900} = 0.092 m
$$


(b) The temperature after 60 minutes at the depth $x$ = $\delta_{0.01}$ is calcualted using

$$
\frac{T - T_i}{T_s - T_s} = erfc\left(\eta \right)
$$

$\eta$ as

$$
\eta = \frac{x}{2\sqrt{\alpha t}} = \frac{0.092}{2 \sqrt{7.25 \cdot 10^{-7} \cdot 3600}} = 0.90
$$

The temperature rise can be calculated by rearranging the first equation for the relative temperature rise in semi-infinite solids with a sudden rise in surface temperature to

$$
T = T_i + erfc\left(\eta\right)\left(T_s - T_i \right) = 0 + erfc\left(0.90\right)\left(1000 - 0\right) = 202.8°C
$$


### Rebar temperature

A 300 mm thick concrete slab has reinforcement bars at a depth of 30 mm from the bottom surface. The slab is suddelnly exposed from below by a fire having a constant temperature of $T_f$ = 900°C. Assume the initial temperature of the slab, $T_$ = 20°C, and the termal conductivity of the concrete, $\lambda$ = 1.0 W/mK, density, $\rho$ = 2300 kg/m³, and the specific heat capacity, $c$ = 800 J/kgK.

(a) What is the surface temperature, $T_0$, of the slab after 10 min of fire exposure? Assume the total heat transfer coefficient due to radiation and convection to be constant at $h$ = 75 W/m²K.

(b) How long does it take until the erinforcement reaches a temperature of 500°C. Assume the the total heat transfer coefficient to be infinitely large, i.e. the surface temperature, $T_0$ = $T_f$.

(c) Estimate how long it takes untill the temperature 300 mm from the bottom of the slab, i.e. the upper surface of the slab, has risen by approximately 10°C (assuming that the slab is infinitely thick)?

**Solution**

(a) Assume the slab to be semi-infinite and apply

$$
\frac{T_s - T_i}{T_g - T_i} = 1 - e^{\tfrac{t}{\tau}}\left[ 1 - erf \left( \sqrt{\frac{t}{\tau}} \right) \right]
$$

where

$$
\frac{t}{\tau}=t^2\frac{t}{\lambda \rho c} = 75^2 \frac{10 \cdot 60}{1 \cdot 2300 \cdot 800} = 1.83
$$

By breaking out the surface temperature, $T_s$, from the equation, it can be calculated to $T_s$ = 593°C

(b) Find the temperature, $T\left(x,t\right)$ = 500°C, at depth $x$ using

$$
\frac{T\left(x, t \right) - T_i}{T_s - T_i} = 1 - erf \left( \frac{x}{2 \sqrt{\alpha t}} \right)
$$

By calculating $\alpha$ as

$$
\alpha = \frac{\lambda}{c \rho} = \frac{1}{800 \cdot 2300} = 5.43 \cdot 10^{-7}
$$

and breaking out the error function as

$$
erf \left( \frac{x}{2 \sqrt{\alpha t}} \right) = 1 - \frac{T\left(x, t \right) - T_i}{T_s - T_i} = 0.545
$$

The inverse function of the error function can be found in tables (or by calculating the inverse error function) giving

$$
X = erf^{-1} \left( erf \left( \frac{x}{2 \sqrt{\alpha t}} \right)\right) = \frac{x}{2 \sqrt{\alpha t}} = 0.428
$$

Breaking out $t$ gives

$$
t = \left(\frac{x}{2 \sqrt{\alpha} X}\right)^2 = \left(\frac{0.03}{2 \sqrt{5.43 \cdot 10^{-7}} \cdot 0.428}\right)^2 = 2265\text{ }s
$$

(c) This can be calculated as above or simplified by assuming that the temperature rise, $\Delta T\left(x,t\right)$ = 10°C is approximately 1 % compared to the difference between the surface temperature (or fire temperature in this case), $T_s$ and the initial temperature, $T_i$. For this case, the time can be calculated based on the 1 % temperature penetration depth.

$$
\delta_{0.01} = 0.3 = 3.6 \sqrt{\alpha t}
$$

Breaking out $t$ gives 

$$
t = \frac{\left( \tfrac{x}{3.6}\right)^2}{\alpha} = \frac{\left( \tfrac{0.3}{3.6}\right)^2}{5.43 \cdot 10^{-7}} = 12 777\text{ }s
$$

or $\approx$ 3.5 h

